version: '3.8'

services:
  database:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: chatapp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-chatapp}
    networks:
      - chatapp-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatapp-backend
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - backend-logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-3001}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-password}@database:27017/${MONGO_DB:-chatapp}?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
    depends_on:
      - database
    networks:
      - chatapp-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
      - BACKEND_ENDPOINT=${BACKEND_ENDPOINT}
    container_name: chatapp-frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - BACKEND_ENDPOINT=${BACKEND_ENDPOINT}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - chatapp-network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: chatapp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - chatapp-network

volumes:
  mongo-data:
    driver: local
  backend-logs:
    driver: local

networks:
  chatapp-network:
    driver: bridge

