version: '3.8'

services:
  database:
    build:
      context: ../mongodb
      dockerfile: Dockerfile
    container_name: chatapp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ../mongodb/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-chatapp}
    networks:
      - chatapp-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: chatapp-backend
    restart: unless-stopped
    volumes:
      - backend-logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-3001}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-password}@database:27017/${MONGO_DB:-chatapp}?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
    depends_on:
      - database
    networks:
      - chatapp-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`chat.elmountahi.dev`) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`))"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
      - BACKEND_ENDPOINT=${BACKEND_ENDPOINT}
    container_name: chatapp-frontend
    environment:
      - NODE_ENV=production
      - BACKEND_ENDPOINT=${BACKEND_ENDPOINT}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - chatapp-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`chat.elmountahi.dev`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v3.0
    container_name: chatapp-traefik
    command:
      - "--log.level=INFO"
      - "--api.insecure=true" # Enable Dashboard on 8080 (optional, good for debugging)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=name@email.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped
    networks:
      - chatapp-network

volumes:
  mongo-data:
    driver: local
  backend-logs:
    driver: local

networks:
  chatapp-network:
    driver: bridge
