version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatapp-backend
    restart: unless-stopped
    volumes:
      - backend-logs:/app/logs
    ports:
      - "3001"

volumes:
  backend-logs:
    driver: local
